// <auto-generated />
using System;
using ClockingManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClockingManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807122320_AddDepartmentPayrollPolicy")]
    partial class AddDepartmentPayrollPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClockingManagement.Domain.Entities.AttendanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BiometricConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("biometric_confidence");

                    b.Property<Guid?>("BiometricVerificationSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("biometric_verification_session_id");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("DistanceFromWorkLocationMetres")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("distance_from_work_location_metres");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsAllowedNetwork")
                        .HasColumnType("boolean")
                        .HasColumnName("is_allowed_network");

                    b.Property<bool?>("IsInsideGeofence")
                        .HasColumnType("boolean")
                        .HasColumnName("is_inside_geofence");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("LocationAccuracyMetres")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("location_accuracy_metres");

                    b.Property<DateTimeOffset?>("LocationCapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("location_captured_at_utc");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_method");

                    b.HasKey("Id");

                    b.HasIndex("BiometricVerificationSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_attendance_events_verification_session")
                        .HasFilter("biometric_verification_session_id IS NOT NULL");

                    b.HasIndex("ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_attendance_events_client_event_id");

                    b.HasIndex("EmployeeId", "CapturedAtUtc")
                        .HasDatabaseName("ix_attendance_events_employee_captured_at");

                    b.ToTable("attendance_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_events_confidence", "biometric_confidence IS NULL OR (biometric_confidence >= 0 AND biometric_confidence <= 100)");

                            t.HasCheckConstraint("ck_attendance_events_distance", "distance_from_work_location_metres IS NULL OR distance_from_work_location_metres >= 0");

                            t.HasCheckConstraint("ck_attendance_events_latitude", "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)");

                            t.HasCheckConstraint("ck_attendance_events_location_accuracy", "location_accuracy_metres IS NULL OR location_accuracy_metres >= 0");

                            t.HasCheckConstraint("ck_attendance_events_longitude", "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)");
                        });
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.BiometricVerificationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_method");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_biometric_sessions_token_hash");

                    b.HasIndex("EmployeeId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_biometric_sessions_employee_expiry");

                    b.ToTable("biometric_verification_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_biometric_sessions_confidence", "confidence >= 0 AND confidence <= 100");
                        });
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_departments_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.DepartmentPayrollPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_salary");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DeductMissingHours")
                        .HasColumnType("boolean")
                        .HasColumnName("deduct_missing_hours");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("ExpectedMonthlyHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("expected_monthly_hours");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("OvertimeMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overtime_multiplier");

                    b.Property<bool>("PayOvertime")
                        .HasColumnType("boolean")
                        .HasColumnName("pay_overtime");

                    b.Property<int>("StandardBreakMinutesPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("standard_break_minutes_per_day");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "EffectiveFrom")
                        .HasDatabaseName("ix_department_payroll_policies_department_effective_from");

                    b.ToTable("department_payroll_policies", (string)null);
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_location_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_email");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_employee_number");

                    b.HasIndex("WorkLocationId")
                        .HasDatabaseName("ix_employees_work_location_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.WorkLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<int>("AllowedRadiusMetres")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_radius_metres");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int>("MaximumLocationAccuracyMetres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("maximum_location_accuracy_metres");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<bool>("RequireGeofence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("require_geofence");

                    b.Property<bool>("RequireIpMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("require_ip_match");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Africa/Johannesburg")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_work_locations_name");

                    b.ToTable("work_locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_locations_accuracy_positive", "maximum_location_accuracy_metres > 0");

                            t.HasCheckConstraint("ck_work_locations_latitude", "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)");

                            t.HasCheckConstraint("ck_work_locations_longitude", "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)");

                            t.HasCheckConstraint("ck_work_locations_radius_positive", "allowed_radius_metres > 0");
                        });
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.WorkLocationAllowedNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NetworkCidr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("network_cidr");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_location_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkLocationId", "NetworkCidr")
                        .IsUnique()
                        .HasDatabaseName("ux_work_location_networks_location_cidr");

                    b.ToTable("work_location_allowed_networks", (string)null);
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.AttendanceEvent", b =>
                {
                    b.HasOne("ClockingManagement.Domain.Entities.BiometricVerificationSession", "BiometricVerificationSession")
                        .WithMany()
                        .HasForeignKey("BiometricVerificationSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClockingManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("AttendanceEvents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BiometricVerificationSession");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.BiometricVerificationSession", b =>
                {
                    b.HasOne("ClockingManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("BiometricVerificationSessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.DepartmentPayrollPolicy", b =>
                {
                    b.HasOne("ClockingManagement.Domain.Entities.Department", "Department")
                        .WithMany("PayrollPolicies")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ClockingManagement.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClockingManagement.Domain.Entities.WorkLocation", "WorkLocation")
                        .WithMany("Employees")
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.WorkLocationAllowedNetwork", b =>
                {
                    b.HasOne("ClockingManagement.Domain.Entities.WorkLocation", "WorkLocation")
                        .WithMany("AllowedNetworks")
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("PayrollPolicies");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceEvents");

                    b.Navigation("BiometricVerificationSessions");
                });

            modelBuilder.Entity("ClockingManagement.Domain.Entities.WorkLocation", b =>
                {
                    b.Navigation("AllowedNetworks");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
